
//=======================Command Set ========================//

//Software RESET Operations
#define RESET_ENABLE 0x66
#define RESET_MEMORY 0x99

//READ ID Operations
#define READ_ID 0x9F
#define MULTIPLE_IO_READ_ID 0xAF
#define READ_SERIAL_FLASH_DISCOVERY_PARAMETER 0x5A 

//READ MEMORY Operations
#define READ 0x03 
#define FAST_READ 0x0B 
#define DUAL_OUTPUT_FAST_READ 0x3B 
#define DUAL_IO_FAST_READ 0xBB 
#define QUAD_OUTPUT_FAST_READ 0x6B
#define QUAD_INPUT_OUTPUT_FAST_READ 0xEB 
#define DTR_FAST_READ 0x0D 
#define DTR_DUAL_OUTPUT_FAST_READ 0x3D 
#define DTR_DUAL_IO_FAST_READ 0xBD 
#define DTR_QUAD_OUTPUT_FAST_READ 0x6D 
#define DTR_QUAD_IO_FAST_READ 0xED
#define QUAD_IO_WORD_READ 0xE7

//READ MEMORY Operations with 4-Byte Address
#define FOUR_BYTE_READ 0x13 
#define FOUR_BYTE_FAST_READ 0x0C 
#define FOUR_BYTE_DUAL_OUTPUT_FAST_READ 0x3C 
#define FOUR_BYTE_DUAL_IO_FAST_READ 0xBC 
#define FOUR_BYTE_QUAD_OUTPUT_FAST_READ 0x6C 
#define FOUR_BYTE_QUAD_IO_FAST_READ 0xEC 
#define FOUR_BYTE_DTR_FAST_READ 0x0E 
#define FOUR_BYTE_DTR_DUAL_IO_FAST_READ 0xBE 
#define FOUR_BYTE_DTR_QUAD_IO_FAST_READ 0xEE 

//WRITE Operations
#define WRITE_ENABLE 0x06
#define WRITE_DISABLE 0x04

//READ REGISTER Operations
#define READ_STATUS_REGISTER 0x05
#define READ_FLAG_STATUS_REGISTER 0x70
#define READ_NONVOLATILE_CONFIGURATION_REGISTER 0xB5
#define READ_VOLATILE_CONFIGURATION_REGISTER 0x85
#define READ_ENHANCED_VOLATILE_CONFIGURATION_REGISTER 0x65
#define READ_EXTENDED_ADDRESS_REGISTER 0xC8
#define READ_GENERAL_PURPOSE_READ_REGISTER 0x96

//WRITE REGISTER Operations
#define WRITE_STATUS_REGISTER 0x01
#define WRITE_NONVOLATILE_CONFIGURATION_REGISTER 0xB1
#define WRITE_VOLATILE_CONFIGURATION_REGISTER 0x81
#define WRITE_ENHANCED_VOLATILE_CONFIGURATION_REGISTER 0x61
#define WRITE_EXTENDED_ADDRESS_REGISTER 0xC5

//CLEAR FLAG STATUS REGISTER Operation
#define CLEAR_FLAG_STATUS_REGISTER 0x50

//PROGRAM Operations
#define PAGE_PROGRAM 0x02
#define DUAL_INPUT_FAST_PROGRAM 0xA2
#define EXTENDED_DUAL_INPUT_FAST_PROGRAM 0xD2
#define QUAD_INPUT_FAST_PROGRAM 0x32
#define EXTENDED_QUAD_INPUT_FAST_PROGRAM 0x38

//PROGRAM Operations with 4-Byte Address
#define FOUR_BYTE_PAGE_PROGRAM 0x12
#define FOUR_BYTE_QUAD_INPUT_FAST_PROGRAM 0x34
#define FOUR_BYTE_QUAD_INPUT_EXTENDED_FAST_PROGRAM 0x3E

//ERASE Operations
#define SUBSECTOR_ERASE_32KB 0x52
#define SUBSECTOR_ERASE_4KB 0x20
#define SECTOR_ERASE 0xD8
#define BULK_ERASE 0xC7

//ERASE Operations with 4-Byte Address
#define FOUR_BYTE_SECTOR_ERASE 0xDC 
#define FOUR_BYTE_4KB_SUBSECTOR_ERASE 0x21
#define FOUR_BYTE_32KB_SUBSECTOR_ERASE 0x5C

//SUSPEND/RESUME Operations
#define PROGRAM_ERASE_SUSPEND 0x75
#define PROGRAM_ERASE_RESUME 0x7A

//ONE-TIME PROGRAMMABLE (OTP) Operations
#define READ_OTP_ARRAY 0x4B
#define PROGRAM_OTP_ARRAY 0x42

//4-BYTE ADDRESS MODE Operations
#define ENTER_FOUR_BYTE_ADDRESS_MODE 0xB7
#define EXIT_FOUR_BYTE_ADDRESS_MODE 0xE9

//QUAD PROTOCOL Operations
#define ENTER_QUAD_IO_MODE 0x35 
#define RESET_QUAD_IO_MODE 0xF5 

//Deep Power-Down Operations
#define ENTER_DEEP_POWER_DOWN 0xB9
#define RELEASE_FROM_DEEP_POWER_DOWN 0xAB

//ADVANCED SECTOR PROTECTION Operations
#define READ_SECTOR_PROTECTION 0x2D 
#define PROGRAM_SECTOR_PROTECTION 0x2C 
#define READ_VOLATILE_LOCK_BITS 0xE8 
#define WRITE_VOLATILE_LOCK_BITS 0xE5 
#define READ_NONVOLATILE_LOCK_BITS 0xE2 
#define WRITE_NONVOLATILE_LOCK_BITS 0xE3 
#define ERASE_NONVOLATILE_LOCK_BITS 0xE4 
#define READ_GLOBAL_FREEZE_BIT 0xA7 
#define WRITE_GLOBAL_FREEZE_BIT 0xA6 
#define READ_PASSWORD 0x27 
#define WRITE_PASSWORD 0x28 
#define UNLOCK_PASSWORD 0x29

//ADVANCED SECTOR PROTECTION Operations with 4-Byte Address
#define FOUR_BYTE_READ_VOLATILE_LOCK_BITS 0xE0  
#define FOUR_BYTE_WRITE_VOLATILE_LOCK_BITS 0xE1 

//ADVANCED FUNCTION INTERFACE Operations
#define INTERFACE_ACTIVATION 0x9B
#define CYCLIC_REDUNDANCY_CHECK 0x9B

